name: Update Submodules

on:
  workflow_dispatch:     # 手动触发
  schedule:
    - cron: "0 3 * * *"  # 每天凌晨3点自动运行（UTC 时间）

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main repo
        uses: actions/checkout@v4
        with:
          submodules: true   # 初始化子模块
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update submodules to latest commit
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # 更新每个 submodule 到远程分支最新
          git submodule foreach '
            branch=$(git config -f $toplevel/.gitmodules submodule.$name.branch || echo main);
            git fetch origin $branch;
            git checkout $branch;
            git pull origin $branch;
          '

          # 检查是否有子模块变化
          if git status --porcelain | grep "M "; then
            echo "Submodules updated, committing changes..."
            git add .
            git commit -m "chore: update submodules to latest"
            git push origin HEAD
          else
            echo "No submodule changes detected."
          fi
